### ISSUE TITLE
所有的网络请求都有警告

### ISSUE THREAD

**Issue by jinlinupup** [kangdongpu/WanAndroid#5]
所有的网络请求都报nchecked call to 'subscribe(Observer<? super T>)' as a member of raw type 'io.reactivex.Observable'警告~

比如：
![image](https://user-images.githubusercontent.com/25645533/50277785-52069980-0480-11e9-9581-8f377441f608.png)

**Comment by kangdongpu** [comment]
忽略警告就行了  这个不影响

**Comment by kangdongpu** [comment]
代码更新了。
